service: job-invoker-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
  memorySize: 128
  timeout: 4
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "lambda:InvokeFunction"
  #       - "lambda:InvokeAsync"
  #     Resource: "*"

functions:
  health:
    handler: endpoints/health.index
    events:
      - httpApi:
          path: /health
          method: get
  invoke:
    handler: endpoints/invokeJob.index
    events:
      - httpApi:
          path: /v1/module/{moduleName}/job/{jobName}/invoke
          method: post
  invokeWithId:
    handler: endpoints/invokeJobWithId.index
    events:
      - httpApi:
          path: /v1/module/{moduleName}/job/{jobName}/invoke/{invocationId}
          method: post
  statusById:
    handler: endpoints/statusByInvocationId.index
    events:
      - httpApi:
          path: /v1/module/{moduleName}/job/{jobName}/invoke/{invocationId}
          method: get

plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true
