service: job-invoker-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
  memorySize: 128
  timeout: 4
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - "lambda:InvokeFunction"
  #       - "lambda:InvokeAsync"
  #     Resource: "*"

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /health
          method: get
  inovoke:
    handler: handler.invokeJob
    events:
      - httpApi:
          path: /v1/Module/{moduleName}/Jobs/{jobName}/Invoke
          method: post
  inovokeWithId:
    handler: handler.invokeJobWithId
    events:
      - httpApi:
          path: /v1/Module/{moduleName}/Jobs/{jobName}/Invoke/{invocationId}
          method: post

plugins:
  - serverless-offline
